-- Add content section visibility flags

ALTER TABLE public.opportunities
  ADD COLUMN IF NOT EXISTS show_header BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_role_overview BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_eligibility_skills BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_introduction BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_program_overview BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_domains BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_eligibility_criteria BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_how_to_apply BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_faqs BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_listing_details BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS show_share BOOLEAN DEFAULT TRUE;
