-- Fix Marketplace Item Deletion Issue
-- This script ensures that when an item is deleted, its related orders/history are handled safely.

-- 1. Drop existing FK constraint on marketplace_orders (constraint name might vary, so we try standardized names or brute)
-- We'll try common names generated by Postgres.
ALTER TABLE public.marketplace_orders
DROP CONSTRAINT IF EXISTS marketplace_orders_item_id_fkey;

-- 2. Re-add FK with CASCADE DELETE
-- This means if a user deletes their item, the order history effectively vanishes too.
-- This is acceptable for a "delete listing" action in this MVP context.
ALTER TABLE public.marketplace_orders
ADD CONSTRAINT marketplace_orders_item_id_fkey
FOREIGN KEY (item_id)
REFERENCES public.marketplace_items(id)
ON DELETE CASCADE;

-- 3. Ensure RLS Policy for Delete Exists
DROP POLICY IF EXISTS "Sellers can delete their items" ON public.marketplace_items;

CREATE POLICY "Sellers can delete their items"
ON public.marketplace_items
FOR DELETE
USING (auth.uid() = seller_id);

-- 4. Ensure authenticated users have permissions
GRANT DELETE ON public.marketplace_items TO authenticated;
