-- Seed 3 dummy opportunities (internship / job / campus ambassador)

INSERT INTO public.opportunities (
  slug, title, company, company_logo, category, industry, type, work_mode, location,
  duration, stipend_text, stipend_min, stipend_max, stipend_currency, work_hours, employment_type,
  experience, eligibility, education, required_skills, branches_allowed, year_of_study, age_limit,
  description, introduction, program_overview, domains, eligibility_criteria, how_to_apply, faqs,
  apply_by, posted_at, updated_at, valid_through, openings, open_method, application_fee, apply_url, is_paid
) VALUES
(
  'outreachy-remote-internship-2026-demo',
  'Outreachy Remote Internship 2026 (Demo)',
  'Outreachy',
  'https://internshipshub.in/logos/outreachy.png',
  'Software',
  'Open Source',
  'Internship',
  'Remote',
  'Remote',
  '12 weeks',
  'Paid; varies by region (Expected/Indicative)',
  1500,
  3600,
  'USD',
  'Full-time remote',
  'Intern',
  'Proof of coding/docs/design contributions',
  'Applicants from underrepresented groups in tech; must meet Outreachy rules',
  'Students or career changers; no degree requirement',
  '["Git workflows","Language fit for chosen project","Async communication"]'::jsonb,
  '["Computer Science","Information Technology","Electronics","Any with coding/docs/design"]'::jsonb,
  'UG/PG/recent grads as per rules',
  'Per Outreachy policy',
  'Fully remote, paid internships with OSS orgs focusing on diversity and inclusion.',
  'Outreachy offers paid, remote internships with open-source organizations to support underrepresented groups in tech.',
  'Interns contribute to production OSS with mentor support. Work is full-time remote over ~12 weeks with milestone evaluations and stipends paid in tranches.',
  '["Web/backend tooling","Data/ML and scientific software","Docs, UX, community operations"]'::jsonb,
  '["Must meet Outreachy rules on representation and location","Demonstrated fit to chosen project; contribution period required"]'::jsonb,
  '["Pick a project and join its communication channel","Make contributions during the contribution period","Submit the application with proposal and contribution evidence","Await mentor review"]'::jsonb,
  '[{"question":"Is it paid?","answer":"Yes, stipends are paid in regional bands (Expected/Indicative)."},{"question":"Fully remote?","answer":"Yes, entire program is remote."},{"question":"Do I need to be a student?","answer":"No; career changers allowed per rules."}]'::jsonb,
  '2026-03-24',
  '2026-02-25',
  '2026-02-25',
  '2026-03-24',
  50,
  'External portal',
  0,
  'https://www.outreachy.org/apply/',
  true
),
(
  'goldman-analyst-intern-2026-demo',
  'Analyst Internship 2026 (Demo)',
  'Goldman Sachs',
  'https://upload.wikimedia.org/wikipedia/commons/6/61/Goldman_Sachs.svg',
  'Finance',
  'Investment Banking',
  'Internship',
  'Onsite',
  'Mumbai',
  '10 weeks',
  '₹40,000 - ₹60,000 / month',
  40000,
  60000,
  'INR',
  'Full-time onsite',
  'Intern',
  'Analytical aptitude, Excel/PowerPoint proficiency',
  'Strong academic record; finance coursework preferred',
  'Final-year undergraduates or postgraduates',
  '["Financial modeling","Excel","PowerPoint","Business communication"]'::jsonb,
  '["Commerce","Economics","Engineering","Management"]'::jsonb,
  'Final year / PG',
  '18+',
  'Work on live deals, financial analysis, and market research with a mentor-led team.',
  'This internship introduces core investment banking workflows with real client exposure.',
  'You will assist in pitch decks, market comps, and financial modeling across sectors.',
  '["M&A","Capital Markets","Industry Research"]'::jsonb,
  '["Minimum 7.5 CGPA or equivalent","Strong quantitative skills"]'::jsonb,
  '["Apply through the official portal","Complete aptitude assessment","Attend interviews"]'::jsonb,
  '[{"question":"Is prior finance experience required?","answer":"Preferred but not mandatory."},{"question":"Is accommodation provided?","answer":"No, candidates must arrange accommodation."}]'::jsonb,
  '2026-04-10',
  '2026-03-05',
  '2026-03-05',
  '2026-04-10',
  25,
  'External portal',
  0,
  'https://www.goldmansachs.com/careers/',
  true
),
(
  'campus-ambassador-growth-2026-demo',
  'Campus Ambassador - Growth (Demo)',
  'Campulsy',
  'https://dummyimage.com/200x200/111827/ffffff&text=Campulsy',
  'Marketing',
  'Education',
  'Campus Ambassador',
  'Hybrid',
  'Bengaluru',
  '6 months',
  'Performance-based incentives + certificates',
  null,
  null,
  'INR',
  'Part-time (6-8 hrs/week)',
  'Ambassador',
  'Good communication, basic social media knowledge',
  'Active on campus, event coordination skills preferred',
  'Any stream',
  '["Communication","Event promotion","Social media"]'::jsonb,
  '["Any branch"]'::jsonb,
  'Any year',
  '17+',
  'Represent Campulsy on campus, drive signups, and organize student outreach.',
  'Work closely with the growth team to expand the student community.',
  'Monthly targets with mentorship and exclusive access to community events.',
  '["Campus events","Community outreach","Social media campaigns"]'::jsonb,
  '["Must be currently enrolled","Attend onboarding workshop"]'::jsonb,
  '["Fill the application form","Complete onboarding call","Start campus outreach"]'::jsonb,
  '[{"question":"Is this paid?","answer":"Incentive-based with performance bonuses."},{"question":"Do I get a certificate?","answer":"Yes, after successful completion."}]'::jsonb,
  '2026-05-01',
  '2026-03-01',
  '2026-03-01',
  '2026-05-01',
  100,
  'Internal form',
  0,
  'https://campulsy.example.com/apply',
  false
) ON CONFLICT (slug) DO NOTHING;

-- Seed 10 more dummy opportunities (across Internship / Campus Ambassador / Swags & Certification)

INSERT INTO public.opportunities (
  slug, title, company, company_logo, category, industry, type, work_mode, location,
  duration, stipend_text, stipend_min, stipend_max, stipend_currency, work_hours, employment_type,
  experience, eligibility, education, required_skills, branches_allowed, year_of_study, age_limit,
  description, introduction, program_overview, domains, eligibility_criteria, how_to_apply, faqs,
  apply_by, posted_at, updated_at, valid_through, openings, open_method, application_fee, apply_url, is_paid
) VALUES
(
  'nimbus-ai-research-intern-2026-demo',
  'Nimbus AI Research Intern (Demo)',
  'Nimbus Labs',
  'https://dummyimage.com/200x200/1f2937/ffffff&text=Nimbus',
  'Data Science',
  'AI',
  'Internship',
  'Remote',
  'Remote',
  '8 weeks',
  '₹30,000 - ₹45,000 / month',
  30000,
  45000,
  'INR',
  'Full-time remote',
  'Intern',
  'ML basics, Python, research aptitude',
  'Strong coding fundamentals and interest in ML research',
  'UG/PG in CS/AI/Statistics preferred',
  '["Python","Pandas","PyTorch","Research writing"]'::jsonb,
  '["Computer Science","Data Science","Statistics"]'::jsonb,
  'Any year',
  '18+',
  'Support model experiments, literature review, and evaluation pipelines.',
  'Work with researchers on model benchmarking and dataset curation.',
  'Weekly sprints, mentorship, and a final research presentation.',
  '["NLP","Vision","Model evaluation"]'::jsonb,
  '["GitHub profile required","Basic ML knowledge"]'::jsonb,
  '["Apply via the official portal","Complete screening task","Interview with mentor"]'::jsonb,
  '[{"question":"Is it remote?","answer":"Yes, fully remote."},{"question":"Is prior research required?","answer":"Not mandatory but preferred."}]'::jsonb,
  '2026-04-18',
  '2026-03-06',
  '2026-03-06',
  '2026-04-18',
  12,
  'External portal',
  0,
  'https://nimbus.example.com/careers/intern',
  true
),
(
  'pixelforge-product-design-intern-2026-demo',
  'Product Design Internship (Demo)',
  'PixelForge',
  'https://dummyimage.com/200x200/0f172a/ffffff&text=PixelForge',
  'Design',
  'SaaS',
  'Internship',
  'Hybrid',
  'Pune',
  '10 weeks',
  '₹20,000 - ₹30,000 / month',
  20000,
  30000,
  'INR',
  'Hybrid (3 days office)',
  'Intern',
  'Portfolio, basic UX understanding',
  'Design aptitude and attention to detail',
  'Design/CS/Related fields',
  '["Figma","Wireframing","UI basics"]'::jsonb,
  '["Design","Computer Science","Any branch"]'::jsonb,
  'Any year',
  '18+',
  'Design interfaces for real product modules and collaborate with PM/Engineering.',
  'Work on user flows, wireframes, and UI polish with design mentors.',
  'Hands-on product design with weekly critique sessions.',
  '["Design systems","Feature UX","Usability testing"]'::jsonb,
  '["Portfolio link required","Basic UX knowledge"]'::jsonb,
  '["Submit portfolio","Complete design task","Interview"]'::jsonb,
  '[{"question":"Is this paid?","answer":"Yes, monthly stipend."},{"question":"Is remote allowed?","answer":"Hybrid only."}]'::jsonb,
  '2026-04-22',
  '2026-03-07',
  '2026-03-07',
  '2026-04-22',
  8,
  'External portal',
  0,
  'https://pixelforge.example.com/careers',
  true
),
(
  'orbitly-growth-marketing-intern-2026-demo',
  'Growth Marketing Intern (Demo)',
  'Orbitly',
  'https://dummyimage.com/200x200/111827/ffffff&text=Orbitly',
  'Marketing',
  'E-commerce',
  'Internship',
  'Onsite',
  'Delhi NCR',
  '12 weeks',
  '₹15,000 - ₹20,000 / month',
  15000,
  20000,
  'INR',
  'Full-time onsite',
  'Intern',
  'Basic marketing, analytics',
  'Good communication and marketing interest',
  'Any discipline',
  '["Marketing","Content","Analytics"]'::jsonb,
  '["Any branch"]'::jsonb,
  'Any year',
  '18+',
  'Support campaigns, track growth experiments, and manage creator outreach.',
  'Learn growth loops and campaign ops in a fast-paced team.',
  'Weekly goals, reporting, and mentorship.',
  '["Campaign management","Creator outreach"]'::jsonb,
  '["Strong communication skills"]'::jsonb,
  '["Apply online","Complete task","Interview with team"]'::jsonb,
  '[{"question":"Remote option?","answer":"No, onsite."}]'::jsonb,
  '2026-04-25',
  '2026-03-07',
  '2026-03-07',
  '2026-04-25',
  20,
  'External portal',
  0,
  'https://orbitly.example.com/careers/intern',
  true
),
(
  'quarkstack-backend-intern-2026-demo',
  'Backend Engineering Intern (Demo)',
  'QuarkStack',
  'https://dummyimage.com/200x200/111827/ffffff&text=Quark',
  'Software',
  'Fintech',
  'Internship',
  'Remote',
  'Remote',
  '12 weeks',
  '₹35,000 - ₹55,000 / month',
  35000,
  55000,
  'INR',
  'Full-time remote',
  'Intern',
  'Data structures, backend fundamentals',
  'Strong CS basics',
  'CS/IT/Related',
  '["Node.js","SQL","APIs"]'::jsonb,
  '["Computer Science","Information Technology"]'::jsonb,
  'Any year',
  '18+',
  'Build APIs and internal services with senior engineering guidance.',
  'Hands-on development with code reviews and performance tuning.',
  'Work on production-grade services with mentorship.',
  '["APIs","Microservices","Databases"]'::jsonb,
  '["GitHub or project links"]'::jsonb,
  '["Apply via portal","Coding test","Technical interview"]'::jsonb,
  '[{"question":"Is it remote?","answer":"Yes, fully remote."}]'::jsonb,
  '2026-04-28',
  '2026-03-08',
  '2026-03-08',
  '2026-04-28',
  10,
  'External portal',
  0,
  'https://quarkstack.example.com/careers',
  true
),
(
  'skillpulse-campus-ambassador-tech-2026-demo',
  'Campus Ambassador - Tech (Demo)',
  'SkillPulse',
  'https://dummyimage.com/200x200/111827/ffffff&text=SkillPulse',
  'Marketing',
  'Education',
  'Campus Ambassador',
  'Hybrid',
  'Hyderabad',
  '4 months',
  'Incentives + certificates',
  null,
  null,
  'INR',
  'Part-time (5-6 hrs/week)',
  'Ambassador',
  'Campus leadership, communication',
  'Active on campus and event coordination',
  'Any stream',
  '["Communication","Leadership","Community building"]'::jsonb,
  '["Any branch"]'::jsonb,
  'Any year',
  '17+',
  'Promote tech events, drive signups, and build student communities.',
  'Work with the outreach team to run campus activations.',
  'Targets with performance-based rewards.',
  '["Campus events","Workshops"]'::jsonb,
  '["Currently enrolled"]'::jsonb,
  '["Apply online","Complete onboarding","Start campus outreach"]'::jsonb,
  '[{"question":"Is it paid?","answer":"Incentives based."}]'::jsonb,
  '2026-05-05',
  '2026-03-08',
  '2026-03-08',
  '2026-05-05',
  80,
  'Internal form',
  0,
  'https://skillpulse.example.com/apply',
  false
),
(
  'edusphere-campus-ambassador-community-2026-demo',
  'Campus Ambassador - Community (Demo)',
  'EduSphere',
  'https://dummyimage.com/200x200/0f172a/ffffff&text=EduSphere',
  'Marketing',
  'Education',
  'Campus Ambassador',
  'Hybrid',
  'Mumbai',
  '5 months',
  'Swag + certificate + performance rewards',
  null,
  null,
  'INR',
  'Part-time (4-6 hrs/week)',
  'Ambassador',
  'Outreach, social media',
  'Campus engagement skills',
  'Any stream',
  '["Social media","Event promotion"]'::jsonb,
  '["Any branch"]'::jsonb,
  'Any year',
  '17+',
  'Lead student outreach and build a campus chapter.',
  'Grow community presence with mentorship.',
  'Monthly goals and recognition.',
  '["Community outreach","Campus campaigns"]'::jsonb,
  '["Must be enrolled"]'::jsonb,
  '["Apply online","Attend orientation","Start outreach"]'::jsonb,
  '[{"question":"Remote?","answer":"Hybrid with campus activities."}]'::jsonb,
  '2026-05-08',
  '2026-03-08',
  '2026-03-08',
  '2026-05-08',
  60,
  'Internal form',
  0,
  'https://edusphere.example.com/ambassador',
  false
),
(
  'novaed-campus-ambassador-events-2026-demo',
  'Campus Ambassador - Events (Demo)',
  'NovaEd',
  'https://dummyimage.com/200x200/111827/ffffff&text=NovaEd',
  'Marketing',
  'Education',
  'Campus Ambassador',
  'Hybrid',
  'Chennai',
  '4 months',
  'Swag + certificate',
  null,
  null,
  'INR',
  'Part-time (4-6 hrs/week)',
  'Ambassador',
  'Event management, outreach',
  'Active campus member',
  'Any stream',
  '["Event management","Outreach"]'::jsonb,
  '["Any branch"]'::jsonb,
  'Any year',
  '17+',
  'Organize events, coordinate volunteers, and promote programs.',
  'Work with community team on campus activations.',
  'Recognition and swag on completion.',
  '["Campus events","Workshops"]'::jsonb,
  '["Currently enrolled"]'::jsonb,
  '["Apply online","Interview","Onboarding"]'::jsonb,
  '[{"question":"Paid?","answer":"Performance incentives + swag."}]'::jsonb,
  '2026-05-12',
  '2026-03-08',
  '2026-03-08',
  '2026-05-12',
  50,
  'Internal form',
  0,
  'https://novaed.example.com/ambassador',
  false
),
(
  'openguild-oss-contribution-challenge-2026-demo',
  'OSS Contribution Challenge (Demo)',
  'OpenGuild',
  'https://dummyimage.com/200x200/0f172a/ffffff&text=OpenGuild',
  'Software',
  'Open Source',
  'Swags and Certification',
  'Remote',
  'Remote',
  '6 weeks',
  'Swag kit + certification',
  null,
  null,
  'INR',
  'Flexible',
  'Contributor',
  'Git basics, OSS interest',
  'Open to all learners',
  'Any stream',
  '["Git","Open source basics"]'::jsonb,
  '["Any branch"]'::jsonb,
  'Any year',
  '16+',
  'Contribute to OSS repos and earn a swag kit + certificate.',
  'Guided tasks to help you start OSS contributions.',
  'Weekly tasks and community support.',
  '["Docs","Frontend fixes","Community tasks"]'::jsonb,
  '["Public GitHub profile"]'::jsonb,
  '["Register","Join community","Complete tasks"]'::jsonb,
  '[{"question":"Paid?","answer":"No, swag and certificate only."}]'::jsonb,
  '2026-04-30',
  '2026-03-08',
  '2026-03-08',
  '2026-04-30',
  200,
  'External portal',
  0,
  'https://openguild.example.com/challenge',
  false
),
(
  'byteworks-brand-advocacy-quest-2026-demo',
  'Brand Advocacy Quest (Demo)',
  'ByteWorks',
  'https://dummyimage.com/200x200/111827/ffffff&text=ByteWorks',
  'Marketing',
  'Technology',
  'Swags and Certification',
  'Remote',
  'Remote',
  '4 weeks',
  'Swag box + certificate',
  null,
  null,
  'INR',
  'Flexible',
  'Contributor',
  'Communication and social media',
  'Open to all learners',
  'Any stream',
  '["Social media","Content creation"]'::jsonb,
  '["Any branch"]'::jsonb,
  'Any year',
  '16+',
  'Promote brand campaigns and earn rewards.',
  'Community challenge focused on content and engagement.',
  'Weekly tasks with leaderboard.',
  '["Content","Community engagement"]'::jsonb,
  '["Public social profile"]'::jsonb,
  '["Register","Complete tasks","Submit proof"]'::jsonb,
  '[{"question":"Stipend?","answer":"No, swag and certificate only."}]'::jsonb,
  '2026-04-26',
  '2026-03-08',
  '2026-03-08',
  '2026-04-26',
  150,
  'External portal',
  0,
  'https://byteworks.example.com/quest',
  false
),
(
  'insightarc-community-research-sprint-2026-demo',
  'Community Research Sprint (Demo)',
  'InsightArc',
  'https://dummyimage.com/200x200/0f172a/ffffff&text=InsightArc',
  'Data Science',
  'Research',
  'Swags and Certification',
  'Remote',
  'Remote',
  '5 weeks',
  'Certificate + swag',
  null,
  null,
  'INR',
  'Flexible',
  'Contributor',
  'Research interest, writing',
  'Open to all learners',
  'Any stream',
  '["Research writing","Survey analysis"]'::jsonb,
  '["Any branch"]'::jsonb,
  'Any year',
  '16+',
  'Participate in research tasks and receive certification.',
  'Guided research sprints with mentorship.',
  'Weekly deliverables and feedback.',
  '["Survey analysis","Report writing"]'::jsonb,
  '["Basic research skills"]'::jsonb,
  '["Register","Complete tasks","Submit report"]'::jsonb,
  '[{"question":"Is it paid?","answer":"No, certificate and swag only."}]'::jsonb,
  '2026-04-27',
  '2026-03-08',
  '2026-03-08',
  '2026-04-27',
  120,
  'External portal',
  0,
  'https://insightarc.example.com/sprint',
  false
),
(
  'helio-ops-intern-2026-demo',
  'Operations Intern (Demo)',
  'Helio Logistics',
  'https://dummyimage.com/200x200/111827/ffffff&text=Helio',
  'Management',
  'Logistics',
  'Internship',
  'Onsite',
  'Bengaluru',
  '10 weeks',
  '₹18,000 - ₹22,000 / month',
  18000,
  22000,
  'INR',
  'Full-time onsite',
  'Intern',
  'Excel, process mindset',
  'Operational aptitude',
  'Any stream',
  '["Excel","Process improvement"]'::jsonb,
  '["Any branch"]'::jsonb,
  'Any year',
  '18+',
  'Assist in process ops and reporting for logistics teams.',
  'Exposure to real operational workflows and optimization tasks.',
  'Weekly reviews and mentorship.',
  '["Operations","Process optimization"]'::jsonb,
  '["Strong analytical skills"]'::jsonb,
  '["Apply online","Complete case task","Interview"]'::jsonb,
  '[{"question":"Is this onsite?","answer":"Yes, Bengaluru office."}]'::jsonb,
  '2026-04-20',
  '2026-03-08',
  '2026-03-08',
  '2026-04-20',
  15,
  'External portal',
  0,
  'https://helio.example.com/careers/intern',
  true
) ON CONFLICT (slug) DO NOTHING;
