import sys

file_path = '/Users/riyansh/Cloudburst/src/pages/AdminDashboard.tsx'

with open(file_path, 'r') as f:
    lines = f.readlines()

# Header and AdminDashboard component (1 to 294)
header = lines[:294]

# Find where BlogManager starts (originally 1513, but let's find it by content)
blog_manager_start = -1
for i, line in enumerate(lines):
    if '// --- BLOG & NEWS MANAGER ---' in line:
        blog_manager_start = i
        break

if blog_manager_start == -1:
    print("Could not find BlogManager")
    sys.exit(1)

footer = lines[blog_manager_start:]

# New middle components
middle = [
    "\n",
    "function SidebarItem({ icon: Icon, label, active, collapsed, onClick }: { icon: any, label: string, active: boolean, collapsed: boolean, onClick: () => void }) {\n",
    "    return (\n",
    "        <button\n",
    "            onClick={onClick}\n",
    "            className={cn(\n",
    "                \"w-full flex items-center gap-3 px-4 py-3 rounded-2xl text-sm font-bold transition-all duration-300 group relative\",\n",
    "                active\n",
    "                    ? \"bg-primary text-white shadow-xl shadow-primary/20 ring-4 ring-primary/10\"\n",
    "                    : \"text-slate-500 hover:text-slate-900 dark:text-zinc-400 dark:hover:text-zinc-100 hover:bg-slate-100 dark:hover:bg-white/5\",\n",
    "                collapsed && \"justify-center px-0 h-12\"\n",
    "            )}\n",
    "        >\n",
    "            <Icon className={cn(\"w-5 h-5 transition-transform group-hover:scale-110\", active ? \"scale-110\" : \"\")} />\n",
    "            {!collapsed && <span className=\"tracking-tight\">{label}</span>}\n",
    "            {collapsed && (\n",
    "                <div className=\"absolute left-full ml-4 px-3 py-1.5 bg-[#0B0B0C] text-white text-[10px] font-black uppercase tracking-widest rounded-xl opacity-0 translate-x-[-10px] group-hover:opacity-100 group-hover:translate-x-0 transition-all z-50 shadow-2xl border border-white/5\">\n",
    "                    {label}\n",
    "                </div>\n",
    "            )}\n",
    "        </button>\n",
    "    );\n",
    "}\n",
    "\n",
    "// --- OVERVIEW SECTION ---\n",
    "function DashboardOverview({ setActiveSection }: { setActiveSection: (s: string) => void }) {\n",
    "    const { data: stats } = useQuery({\n",
    "        queryKey: ['admin-stats'],\n",
    "        queryFn: async () => {\n",
    "            const [users, marketplace, pendingMarketplace, pendingRooms] = await Promise.all([\n",
    "                supabase.from('profiles').select('id', { count: 'exact' }),\n",
    "                supabase.from('marketplace_items').select('id', { count: 'exact' }),\n",
    "                supabase.from('marketplace_items').select('id', { count: 'exact' }).eq('status', 'pending'),\n",
    "                supabase.from('rooms').select('id', { count: 'exact' }).eq('status', 'pending'),\n",
    "            ]);\n",
    "            return {\n",
    "                users: users.count || 0,\n",
    "                marketplace: marketplace.count || 0,\n",
    "                pending: (pendingMarketplace.count || 0) + (pendingRooms.count || 0),\n",
    "            };\n",
    "        }\n",
    "    });\n",
    "    const { data: recentUsers } = useQuery({\n",
    "        queryKey: ['admin-recent-users'],\n",
    "        queryFn: async () => {\n",
    "            const { data } = await supabase.from('profiles').select('*').order('created_at', { ascending: false }).limit(5);\n",
    "            return data || [];\n",
    "        }\n",
    "    });\n",
    "\n",
    "    return (\n",
    "        <div className=\"space-y-8 animate-fade-in\">\n",
    "            {/* Stats Grid */}\n",
    "            <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6\">\n",
    "                <StatCard title=\"Total Users\" value={stats?.users || 0} icon={Users} color=\"text-blue-500\" bg=\"bg-blue-500/10\" />\n",
    "                <StatCard title=\"Marketplace Items\" value={stats?.marketplace || 0} icon={ShoppingBag} color=\"text-orange-500\" bg=\"bg-orange-500/10\" />\n",
    "                <StatCard \n",
    "                    title=\"Pending Approvals\" \n",
    "                    value={stats?.pending || 0} \n",
    "                    icon={ShieldAlert} \n",
    "                    color={stats?.pending && stats.pending > 0 ? \"text-rose-500\" : \"text-muted-foreground\"} \n",
    "                    bg={stats?.pending && stats.pending > 0 ? \"bg-rose-500/10\" : \"bg-muted/10\"} \n",
    "                />\n",
    "            </div>\n",
    "\n",
    "            {/* Quick Actions */}\n",
    "            <div className=\"grid grid-cols-1 md:grid-cols-3 gap-6\">\n",
    "                <Card className=\"col-span-2 border-border/50 shadow-sm\">\n",
    "                    <CardHeader>\n",
    "                        <CardTitle>Quick Actions</CardTitle>\n",
    "                        <CardDescription>Common tasks you perform often.</CardDescription>\n",
    "                    </CardHeader>\n",
    "                    <CardContent className=\"flex flex-col sm:flex-row gap-4\">\n",
    "                        <Button variant=\"outline\" onClick={() => setActiveSection('marketplace')} className=\"gap-2\">Manage Marketplace</Button>\n",
    "                        <Button variant=\"outline\" onClick={() => setActiveSection('blog')} className=\"gap-2\">Manage Blog</Button>\n",
    "                    </CardContent>\n",
    "                </Card>\n",
    "\n",
    "                <Card className=\"bg-primary/5 border-primary/20 shadow-inner\">\n",
    "                    <CardHeader>\n",
    "                        <CardTitle className=\"text-primary flex items-center justify-center md:justify-start gap-2\">\n",
    "                            <ShieldAlert className=\"w-5 h-5\" /> System Status\n",
    "                        </CardTitle>\n",
    "                    </CardHeader>\n",
    "                    <CardContent className=\"flex flex-col items-center text-center md:items-start md:text-left\">\n",
    "                        <div className=\"flex items-center gap-2 mb-2\">\n",
    "                            <span className=\"w-2 h-2 rounded-full bg-green-500 shrink-0 animate-pulse\" />\n",
    "                            <span className=\"text-sm font-medium\">All Systems Operational</span>\n",
    "                        </div>\n",
    "                        <p className=\"text-xs text-muted-foreground\">Database connected. Storage available.</p>\n",
    "                    </CardContent>\n",
    "                </Card>\n",
    "            </div>\n",
    "\n",
    "            {/* Recent Activity Section */}\n",
    "            <div className=\"grid grid-cols-1 lg:grid-cols-2 gap-6\">\n",
    "                <Card className=\"border-border/50 shadow-sm overflow-hidden\">\n",
    "                    <CardHeader className=\"flex flex-row items-center justify-between border-b border-border/50 bg-muted/20\">\n",
    "                        <div>\n",
    "                            <CardTitle className=\"text-lg\">Recent Users</CardTitle>\n",
    "                            <CardDescription>Latest members to join CredSwap.</CardDescription>\n",
    "                        </div>\n",
    "                        <Button variant=\"ghost\" size=\"sm\" onClick={() => setActiveSection('users')} className=\"gap-1\">\n",
    "                            View All <ChevronRight className=\"w-4 h-4\" />\n",
    "                        </Button>\n",
    "                    </CardHeader>\n",
    "                    <CardContent className=\"p-0\">\n",
    "                        <div className=\"divide-y divide-border/50\">\n",
    "                            {recentUsers?.map((user: any) => (\n",
    "                                <div key={user.id} className=\"p-4 flex items-center justify-between group hover:bg-secondary/30 transition-colors\">\n",
    "                                    <div className=\"flex items-center gap-3\">\n",
    "                                        <div className=\"w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold overflow-hidden border border-primary/20\">\n",
    "                                            {user.avatar_url ? (\n",
    "                                                <img src={user.avatar_url} alt=\"\" className=\"w-full h-full object-cover\" />\n",
    "                                            ) : (\n",
    "                                                user.full_name?.charAt(0) || 'U'\n",
    "                                            )}\n",
    "                                        </div>\n",
    "                                        <div>\n",
    "                                            <p className=\"font-bold text-sm tracking-tight\">{user.full_name}</p>\n",
    "                                            <p className=\"text-xs text-muted-foreground truncate max-w-[150px]\">{user.email}</p>\n",
    "                                        </div>\n",
    "                                    </div>\n",
    "                                    <Badge variant={user.is_verified ? \"default\" : \"secondary\"} className=\"text-[10px] uppercase font-black tracking-tighter\">\n",
    "                                        {user.is_verified ? \"Verified\" : \"Regular\"}\n",
    "                                    </Badge>\n",
    "                                </div>\n",
    "                            ))}\n",
    "                        </div>\n",
    "                    </CardContent>\n",
    "                </Card>\n",
    "\n",
    "                <Card className=\"border-border/50 shadow-sm overflow-hidden\">\n",
    "                    <CardHeader className=\"flex flex-row items-center justify-between border-b border-border/50 bg-muted/20\">\n",
    "                        <div>\n",
    "                            <CardTitle className=\"text-lg\">Platform Summary</CardTitle>\n",
    "                            <CardDescription>Key performance indicators.</CardDescription>\n",
    "                        </div>\n",
    "                        <div className=\"p-2 rounded-lg bg-primary/10 text-primary\">\n",
    "                            <TrendingUp className=\"w-5 h-5\" />\n",
    "                        </div>\n",
    "                    </CardHeader>\n",
    "                    <CardContent className=\"p-6\">\n",
    "                        <div className=\"space-y-4\">\n",
    "                            <div className=\"flex justify-between items-center p-3 rounded-xl bg-orange-500/5 border border-orange-500/10\">\n",
    "                                <div className=\"flex items-center gap-3\">\n",
    "                                    <div className=\"p-2 rounded-lg bg-orange-500/20 text-orange-600\">\n",
    "                                        <ShoppingBag className=\"w-4 h-4\" />\n",
    "                                    </div>\n",
    "                                    <span className=\"font-bold text-sm\">Marketplace Velocity</span>\n",
    "                                </div>\n",
    "                                <span className=\"text-xs font-black text-orange-600\">HEALTHY</span>\n",
    "                            </div>\n",
    "                            <div className=\"flex justify-between items-center p-3 rounded-xl bg-blue-500/5 border border-blue-500/10\">\n",
    "                                <div className=\"flex items-center gap-3\">\n",
    "                                    <div className=\"p-2 rounded-lg bg-blue-500/20 text-blue-600\">\n",
    "                                        <Users className=\"w-4 h-4\" />\n",
    "                                    </div>\n",
    "                                    <span className=\"font-bold text-sm\">Retention Rate</span>\n",
    "                                </div>\n",
    "                                <span className=\"text-xs font-black text-blue-600\">88%</span>\n",
    "                            </div>\n",
    "                        </div>\n",
    "                    </CardContent>\n",
    "                </Card>\n",
    "            </div>\n",
    "        </div >\n",
    "    );\n",
    "}\n",
    "\n",
    "function StatCard({ title, value, icon: Icon, color, bg }: { title: string, value: string | number, icon: any, color: string, bg: string }) {\n",
    "    return (\n",
    "        <Card className=\"border-border/50 shadow-sm hover:shadow-md transition-all\">\n",
    "            <CardContent className=\"p-6 flex items-center justify-between\">\n",
    "                <div>\n",
    "                    <p className=\"text-sm font-medium text-muted-foreground mb-1\">{title}</p>\n",
    "                    <h3 className=\"text-3xl font-display font-bold\">{value}</h3>\n",
    "                </div>\n",
    "                <div className={cn(\"w-12 h-12 rounded-xl flex items-center justify-center transition-transform hover:scale-110\", bg, color)}>\n",
    "                    <Icon className=\"w-6 h-6\" />\n",
    "                </div>\n",
    "            </CardContent>\n",
    "        </Card>\n",
    "    );\n",
    "}\n",
    "\n"
]

with open(file_path, 'w') as f:
    f.writelines(header)
    f.writelines(middle)
    f.writelines(footer)
